# generated by datamodel-codegen:
#   filename:  dispense.json
#   timestamp: 2024-07-17T18:47:52+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from sdl.processes.opentrons_utils import OpentronsBaseProcedure, WellLocation, OpentronsParamsMoveToLocation, Offset
from sdl.processes.opentrons_utils1 import OpentronsMoveAction


class DispenseParams(OpentronsParamsMoveToLocation):
    volume: int
    flowRate: float
    wellLocation : Optional[WellLocation] = WellLocation(origin='bottom', offset=Offset(x=0, y=0, z=2))


class Dispense(OpentronsMoveAction[DispenseParams]):
    url = '/runs/{run_id}/commands'
    commandType = 'dispense'
    intent = None

    def execute(self, *args, **kwargs):
        output = self.execute_all(*args, **kwargs)
        return output
