# generated by datamodel-codegen:
#   filename:  drop_tip.json
#   timestamp: 2024-07-17T19:04:20+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from sdl.processes.opentrons_utils import WellLocation, OpentronsBaseProcedure


class DropTipParams(BaseModel):
    pipetteId: str
    labwareId: str
    wellName: str
    wellLocation: WellLocation
    homeAfter: Optional[bool] = None
    alternateDropLocation: Optional[bool] = None


class DropTip(OpentronsBaseProcedure[DropTipParams]):
    url = '/runs/{run_id}/commands'
    commandType = 'dropTip'
    intent = None
