# generated by datamodel-codegen:
#   filename:  dispense.json
#   timestamp: 2024-07-17T18:47:52+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from sdl.Robot.workflow.processes.opentrons_utils import OpentronsBaseProcedure, WellLocation


class DispenseParams(BaseModel):
    labwareId: str
    wellName: str
    pipetteId: str
    volume: int
    flowRate: float
    wellLocation: WellLocation


class Dispense(OpentronsBaseProcedure):
    url: str = '/runs/{run_id}/commands'
    commandType = 'dispense'
    params: DispenseParams
    intent: Optional[str] = None
