# generated by datamodel-codegen:
#   filename:  move_to_well.json
#   timestamp: 2024-07-17T19:04:41+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from sdl.Robot.workflow.processes.opentrons_utils import WellLocation, OpentronsBaseProcedure


class MoveToWellParams(BaseModel):
    labwareId: str
    wellName: str
    pipetteId: str
    wellLocation: WellLocation
    speed: int


class MoveToWell(OpentronsBaseProcedure):
    url: str = '/runs/{run_id}/commands'
    commandType = "moveToWell"
    params: MoveToWellParams
    intent: Optional[str] = None
