# Mock node labels
node_embedding_inputs = {
    "material name": """material name""",
    "material id": """material id number""",
    "material type": """material type""",
    "material composition": """material function""",
    "component name": """component name""",
    "component id": """component id""",
    "component type": """component type""",
    "component composition": """component function""",
    "device name": """device name""",
    "device id": """device id""",
    "device type": """device type""",
    "device composition": """device function""",
    "material": """material or substance""",
    "component": """component""",
    "device": """device""",
    "material concentration": "material concentration ratio",
    "manufacturing": """Manufacturing step""",
    "manufacturing process": """manufacturing process""",
    "measurement process": """measurement process""",
    "measurement": """measurement process or procedure""",
    "device_property": """property of material""",
    "material_property": """property of material""",
    "component_property": """property of component""",
    "condition parameter": """process condition""",
    "process parameter": """process parameter""",
    "material condition": "material contidition",
    "material manufacturing parameter": """material manufacturing parameter""",
    "component manufacturing parameter": """component manufacturing parameter""",
    "device manufacturing parameter": """device manufacturing parameter""",
    "material measurement parameter": """material measurement parameter""",
    "component measurement parameter": """component measurement parameter""",
    "device measurement parameter": """device measurement parameter""",
    "process condition": """process condition""",
    "process quantity": """process quantity""",
    "manufacturing quanity": """manufacturing quantity""",
    "measurement quantity": """measurement quantity""",
    "manufacturing parameter": """manufacturing parameter""",
    "measurement parameter": """measurement parameter""",
    "material ratio": """ material value""",
    "material concentration": "material concentration ratio"
}

embedding_mapper = {
    "material name": "matter",
    "material id": "matter",
    "material type": "matter",
    "material composition": "matter",
    "component name": "matter",
    "component id": "matter",
    "component type": "matter",
    "component composition": "matter",
    "device name": "matter",
    "device id": "matter",
    "device type": "matter",
    "device composition": "matter",
    "material condition": "parameter",
    "material": "matter",
    "component": "matter",
    "device": "matter",
    "manufacturing": "manufacturing",
    "manufacturing process": "manufacturing",
    "measurement process": "measurement",
    "measurement": "measurement",
    "device_property": "property",
    "material_property": "property",
    "component_property": "property",
    "condition parameter": "parameter",
    "process parameter": "parameter",
    "material manufacturing parameter": "parameter",
    "material measurement parameter": "parameter",
    "component manufacturing parameter": "parameter",
    "component measurement parameter": "parameter",
    "device manufacturing parameter": "parameter",
    "device measurement parameter": "parameter",
    "process condition": "parameter",
    "process quantity": "parameter",
    "manufacturing quanity": "parameter",
    "measurement quantity": "parameter",
    "manufacturing parameter": "parameter",
    "material ratio": """property""",
    "measurement parameter": "parameter",
    "material concentration": "property"
}