# # Mock node labels
# node_embedding_inputs = {
#     "material name": """type name description """,
#     "material name abbreviation": """material name abbreviation""",
#     "material id": """identifyer uid  id""",
#     "material composition": """material function""",
#     "component name": """component name""",
#     "component id": """component id""",
#     "component type": """component type""",
#     "component composition": """component function""",
#     "device name": """device name""",
#     "device id": """device id""",
#     "device type": """device type""",
#     "device composition": """device function""",
#     "material": """material substance intermediate""",
#     "component": """component part intermediate""",
#     "device": """device""",
#     "material concentration": "material concentration ratio",
#     "manufacturing": """manufacturing fabrication  modification""",
#     "manufacturing process": """manufacturing process""",
#     "material manufacturing": """material manufacturing""",
#     "component manufacturing": """component process manufacturing""",
#     "device manufacturing": """device process manufacturing""",
#     "material process": """material processing""",
#     "component process": """processing component""",
#     "device process": """device processing""",
#     "material change": """change transformation""",
#     "component change": """component transformation""",
#     "device change": """device transformation""",
#     "material conversion": """material conversion""",
#     "component conversion": """component conversion""",
#     "device conversion": """device conversion""",
#     "measurement process": """measurement process""",
#     "measurement": """measurement process or procedure""",
#     "device_property": """property of material""",
#     "material_property": """property value material""",
#     "component_property": """property of component""",
#     "condition parameter": """process operating condition""",
#     "process parameter": """process operating parameter""",
#     "material condition": "material operating condition",
#     "material manufacturing parameter": """material manufacturing parameter""",
#     "material process parameter": """material process parameter""",
#     "component manufacturing parameter": """component manufacturing parameter""",
#     "material manufacturing condition": """material manufacturing condition""",
#     "material process condition": """material process condition""",
#     "component manufacturing condition": """component manufacturing condition""",
#     "device manufacturing parameter": """device manufacturing parameter""",
#     "material measurement parameter": """material measurement parameter""",
#     "component measurement parameter": """component measurement parameter""",
#     "device measurement parameter": """device measurement parameter""",
#     "process condition": """operational condition""",
#     "process parameter": """process parameter""",
#     "fabrication condition": """operational process condition""",
#     "process quantity": """process quantity""",
#     "manufacturing quanity": """manufacturing quantity""",
#     "measurement quantity": """measurement quantity""",
#     "manufacturing parameter": """manufacturing parameter""",
#     "measurement parameter": """measurement parameter""",
#     "material ratio": """material ratio""",
#     "location": """location of process""",
#     "facility": """facility of process""",
#     "institute": """research institute""",
#     "organization": """research organization""",
# }

# Mock node labels
node_embedding_inputs = {
    "material name": """type name""",
    "material name abbreviation": """Abbreviated material identifier.""",
    "material composition": """material function""",
    "component name": """component name""",
    "component id": """component id""",
    "component type": """component type""",
    "component composition": """component function""",
    "device name": """device name""",
    "device id": """device id""",
    "device type": """device type""",
    "device composition": """device function""",
    "material": """material substance intermediate""",
    "component": """component part intermediate""",
    "device": """device""",
    "material concentration": "material concentration ratio",
    "manufacturing": """manufacturing fabrication  modification""",
    "manufacturing process": """matter manufacturing process""",
    "material manufacturing": """material manufacturing""",
    "component manufacturing": """component process manufacturing""",
    "device manufacturing": """device process manufacturing""",
    "material process": """material processing""",
    "component process": """processing component""",
    "device process": """device processing""",
    "material change": """change transformation""",
    "component change": """component transformation""",
    "device change": """device transformation""",
    "material conversion": """material conversion""",
    "component conversion": """component conversion""",
    "device conversion": """device conversion""",
    "measurement process": """measurement process""",
    # "measurement": """measurement process or procedure""",
    "device_property": """property of value device""",
    "material_property": """property value material""",
    "component_property": """property of component""",
    "condition parameter": """process operating condition""",
    "process parameter": """process operating parameter""",
    "material condition": "material operating condition",
    "material manufacturing parameter": """matter manufacturing parameter""",
    "material process parameter": """matter process parameter""",
    "component manufacturing parameter": """component manufacturing parameter""",
    "material manufacturing condition": """material manufacturing condition""",
    "material process condition": """material process condition""",
    "component manufacturing condition": """component manufacturing condition""",
    "device manufacturing parameter": """device manufacturing parameter""",
    "material measurement parameter": """material measurement parameter""",
    "component measurement parameter": """component measurement parameter""",
    "device measurement parameter": """device measurement parameter""",
    "process condition": """operational condition""",
    "process parameter": """process parameter""",
    "process material parameter": """process material parameter""",
    "fabrication condition": """operational process condition""",
    "process quantity": """process quantity""",
    "manufacturing quanity": """manufacturing quantity""",
    "measurement quantity": """measurement quantity""",
    "manufacturing parameter": """manufacturing parameter""",
    "measurement parameter": """measurement parameter""",
    "material ratio": """material ratio""",
    "location": """location of processing site""",
    "facility": """processing research facility""",
    "institute": """research institute""",
    "organization": """research organization""",
    "instrument": """manufacturing instrument""",
    "metadata_device": """manufacturing device""",
    "laboratory_equipment": """laboratory equipment""",
}

embedding_mapper = {
    "material name": "Matter",
    "material id": "Matter",
    "material type": "Matter",
    "material composition": "Matter",
    "component name": "Matter",
    "component id": "Matter",
    "component type": "Matter",
    "component composition": "Matter",
    "device name": "Matter",
    "device id": "Matter",
    "device type": "Matter",
    "device composition": "Matter",
    "material condition": "Parameter",
    "material": "Matter",
    "component": "Matter",
    "device": "Matter",
    "manufacturing": "Manufacturing",
    "manufacturing process": "Manufacturing",
    "measurement process": "Measurement",
    "measurement": "Measurement",
    "device_property": "Property",
    "material_property": "Property",
    "component_property": "Property",
    "condition parameter": "Parameter",
    "process parameter": "Parameter",
    "material manufacturing parameter": "Parameter",
    "material process parameter": "Parameter",
    "material measurement parameter": "Parameter",
    "component manufacturing parameter": "Parameter",
    "component measurement parameter": "Parameter",
    "device manufacturing parameter": "Parameter",
    "device measurement parameter": "Parameter",
    "process condition": "Parameter",
    "process quantity": "Parameter",
    "manufacturing quanity": "Parameter",
    "measurement quantity": "Parameter",
    "manufacturing parameter": "Parameter",
    "material ratio": """Matter""",
    "measurement parameter": "Parameter",
    "material concentration": "Matter",
    "location": "Metadata",
    "facility": "Metadata",
    "institute": "Metadata",
    "organization": "Metadata",
    "process condition": """Parameter""",
    "process parameter": """Parameter""",
    "fabrication condition": """Parameter""",
    "material name abbreviation": """Matter""",
    "material manufacturing": """Manufacturing""",
    "component manufacturing": """Manufacturing""",
    "device manufacturing": """Manufacturing""",
    "material manufacturing condition": """Parameter""",
    "material process condition": """Parameter""",
    "component manufacturing condition": """Parameter""",
    "material process": """Manufacturing""",
    "component process": """Manufacturing""",
    "device process": """Manufacturing""",
    "material conversion": """Manufacturing""",
    "component conversion": """Manufacturing""",
    "device conversion": """Manufacturing""",
    "material change": """Manufacturing""",
    "component change": """Manufacturing""",
    "device change": """Manufacturing""",
    "process material parameter": """Property""",
    "instrument": """Metadata""",
    "metadata_device": """Metadata""",
    "laboratory_equipment": """Metadata""",
}