# generated by datamodel-codegen:
#   filename:  home_robot.json
#   timestamp: 2024-07-17T18:48:53+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from sdl.Robot.workflow.processes.opentrons_utils import OpentronsBaseProcedure


class HomeRobot(OpentronsBaseProcedure):
    commandType = 'home'
    url: str = '/robot/home'
    params = {}
    intent: Optional[str] = None
