# generated by datamodel-codegen:
#   filename:  pick_up_tip.json
#   timestamp: 2024-07-17T19:02:56+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel

from sdl.Robot.workflow.processes.opentrons_utils import OpentronsBaseProcedure





class PickUpTipParams(BaseModel):
    labwareId: str
    wellName: str
    pipetteId: str


class PickUpTip(OpentronsBaseProcedure):
    commandType = 'pickUpTip'
    url: str = '/runs/{run_id}/commands'
    params: PickUpTipParams
    intent: Optional[str] = None
