# Generated by Django 3.2.16 on 2023-11-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=200, unique=True)),
                ('label', models.CharField(blank=True, choices=[('Matter', 'Matter'), ('Property', 'Property'), ('Parameter', 'Parameter'), ('Measurement', 'Measurement'), ('Manufacturing', 'Manufacturing'), ('Metadata', 'Metadata'), ('No label', 'No label'), (None, 'None')], max_length=200, null=True)),
                ('header_attribute', models.CharField(blank=True, choices=[('identifier', 'Identifier'), ('name', 'Name'), ('value', 'Value'), ('unit', 'Unit'), ('error', 'Error'), ('std', 'Standard deviation'), ('min', 'Minimum'), ('max', 'Maximum'), ('mean', 'Mean'), ('median', 'Median'), ('concentration', 'Concentration'), ('ratio', 'Ratio'), ('batch number', 'Batch'), ('No attribute', 'No attribute'), (None, 'None')], max_length=200, null=True)),
                ('column_attribute', models.CharField(blank=True, choices=[('identifier', 'Identifier'), ('name', 'Name'), ('value', 'Value'), ('unit', 'Unit'), ('error', 'Error'), ('std', 'Standard deviation'), ('min', 'Minimum'), ('max', 'Maximum'), ('mean', 'Mean'), ('median', 'Median'), ('concentration', 'Concentration'), ('ratio', 'Ratio'), ('batch number', 'Batch'), ('No attribute', 'No attribute'), (None, 'None')], max_length=200, null=True)),
                ('sample_column', models.CharField(max_length=200)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImportingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(default='None given')),
                ('html_report', models.TextField(default='None given')),
                ('context', models.CharField(default='None given', max_length=140)),
                ('file_link', models.CharField(default='None given', max_length=100)),
                ('report_file_link', models.CharField(default='None given', max_length=100)),
                ('file_name', models.CharField(default='None given', max_length=100)),
            ],
            options={
                'verbose_name': 'Importing Report',
                'verbose_name_plural': 'Importing Reports',
            },
        ),
        migrations.CreateModel(
            name='LabelClassificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(default='None given')),
                ('html_report', models.TextField(default='None given')),
                ('context', models.CharField(default='None given', max_length=140)),
                ('file_link', models.CharField(default='None given', max_length=100)),
                ('report_file_link', models.CharField(default='None given', max_length=100)),
                ('file_name', models.CharField(default='None given', max_length=100)),
            ],
            options={
                'verbose_name': 'Label Classification Report',
                'verbose_name_plural': 'Label Classification Report',
            },
        ),
    ]
