# Generated by Django 3.2.16 on 2023-08-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField()),
            ],
            options={
                'verbose_name': 'Importing Report',
                'verbose_name_plural': 'Importing Reports',
            },
        ),
    ]
