# Generated by Django 3.2.16 on 2024-02-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulltablecache',
            name='test',
        ),
    ]
