# Generated by Django 3.2.16 on 2023-11-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportingReport',
        ),
    ]
