# Generated by Django 3.2.16 on 2023-11-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0003_attributeclassificationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeExtractionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(default='None given')),
                ('html_report', models.TextField(default='None given')),
                ('context', models.CharField(default='None given', max_length=140)),
                ('file_link', models.CharField(default='None given', max_length=100)),
                ('report_file_link', models.CharField(default='None given', max_length=100)),
                ('file_name', models.CharField(default='None given', max_length=100)),
            ],
            options={
                'verbose_name': 'Node Extraction Report',
                'verbose_name_plural': 'Node Extraction Reports',
            },
        ),
        migrations.AlterModelOptions(
            name='attributeclassificationreport',
            options={'verbose_name': 'Attribute Classification Report', 'verbose_name_plural': 'Attribute Classification Reports'},
        ),
        migrations.AlterModelOptions(
            name='labelclassificationreport',
            options={'verbose_name': 'Label Classification Report', 'verbose_name_plural': 'Label Classification Reports'},
        ),
    ]
