# Generated by Django 3.2.16 on 2024-02-02 10:28

from django.db import migrations, models
import importing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeClassificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(default='None given')),
                ('html_report', models.TextField(default='None given')),
                ('context', models.TextField(blank=True, default='None given', max_length=140, null=True)),
                ('file_link', models.CharField(default='None given', max_length=100)),
                ('report_file_link', models.CharField(default='None given', max_length=100)),
                ('file_name', models.CharField(default='None given', max_length=100)),
            ],
            options={
                'verbose_name': 'Attribute Classification Report',
                'verbose_name_plural': 'Attribute Classification Reports',
            },
        ),
        migrations.CreateModel(
            name='FullTableCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=40000, unique=True)),
                ('validated_graph', models.BooleanField(default=False, verbose_name='Validated Graph')),
                ('test', models.CharField(blank=True, max_length=900, null=True)),
                ('graph', models.JSONField(null=True)),
            ],
            bases=(models.Model, importing.models.Cache),
        ),
        migrations.CreateModel(
            name='ImporterCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=200, unique=True)),
                ('column_label', models.CharField(blank=True, choices=[('Matter', 'Matter'), ('Property', 'Property'), ('Parameter', 'Parameter'), ('Measurement', 'Measurement'), ('Manufacturing', 'Manufacturing'), ('Metadata', 'Metadata'), ('No label', 'No label'), (None, 'None')], max_length=200, null=True)),
                ('header_attribute', models.CharField(blank=True, choices=[('identifier', 'Identifier'), ('name', 'Name'), ('value', 'Value'), ('unit', 'Unit'), ('error', 'Error'), ('std', 'Standard deviation'), ('min', 'Minimum'), ('max', 'Maximum'), ('mean', 'Mean'), ('median', 'Median'), ('concentration', 'Concentration'), ('ratio', 'Ratio'), ('batch_number', 'Batch'), ('No attribute', 'No attribute'), (None, 'None')], max_length=200, null=True)),
                ('column_attribute', models.CharField(blank=True, choices=[('identifier', 'Identifier'), ('name', 'Name'), ('value', 'Value'), ('unit', 'Unit'), ('error', 'Error'), ('std', 'Standard deviation'), ('min', 'Minimum'), ('max', 'Maximum'), ('mean', 'Mean'), ('median', 'Median'), ('concentration', 'Concentration'), ('ratio', 'Ratio'), ('batch_number', 'Batch'), ('No attribute', 'No attribute'), (None, 'None')], max_length=200, null=True)),
                ('sample_column', models.CharField(max_length=200)),
                ('validated_column_label', models.BooleanField(default=False, verbose_name='Validated Col-label')),
                ('validated_column_attribute', models.BooleanField(default=False, verbose_name='Validated Col-attribute')),
                ('validated_header_attribute', models.BooleanField(default=False, verbose_name='Validated Header-attribute')),
            ],
            bases=(importing.models.Cache, models.Model),
        ),
        migrations.CreateModel(
            name='LabelClassificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(default='None given')),
                ('html_report', models.TextField(default='None given')),
                ('context', models.TextField(blank=True, default='None given', max_length=140, null=True)),
                ('file_link', models.CharField(default='None given', max_length=100)),
                ('report_file_link', models.CharField(default='None given', max_length=100)),
                ('file_name', models.CharField(default='None given', max_length=100)),
            ],
            options={
                'verbose_name': 'Label Classification Report',
                'verbose_name_plural': 'Label Classification Reports',
            },
        ),
        migrations.CreateModel(
            name='NodeExtractionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField(default='None given')),
                ('html_report', models.TextField(default='None given')),
                ('context', models.TextField(blank=True, default='None given', max_length=140, null=True)),
                ('file_link', models.CharField(default='None given', max_length=100)),
                ('report_file_link', models.CharField(default='None given', max_length=100)),
                ('file_name', models.CharField(default='None given', max_length=100)),
            ],
            options={
                'verbose_name': 'Node Extraction Report',
                'verbose_name_plural': 'Node Extraction Reports',
            },
        ),
    ]
